apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: frontend
spec:
  replicas: 5

  template:
    metadata:
      name: myapp-rc
      labels:
        app: my
    spec:
      containers:
      - name: nginx-conteiner
        image: nginx