apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploy
  labels:
    app: nginx
    tier: front-end
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 4

  template:
    metadata:
      name: nginx2
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx
        image: nginx
