apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-dr
  labels:
    app: nginx
    tier: front-end
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0      

  selector:
    matchLabels:
      app: myapp
  replicas: 4

  template:
    metadata:
      name: nginx2
      labels:
        app: myapp
    
    spec:
      containers:
      - name: nginx
        image: nginx